"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[character]
success_symbol = "[➜](bold green)"

[package]
disabled = true

[aws]
disabled = true

[python]
python_binary = ["./venv/bin/python", "python", "python3"]
