import = [
	"~/.config/alacritty/gihub_dark_colorblind.yml"
]

[cursor]
style = { shape="Block", blinking="Never" }

[env]
TERM="xterm-256color"
working_directory="~/Work"

[font]
size=15.0
normal = { family = "GeistMono NF", style = "Regular" }

[mouse]
hide_when_typing=true

[scrolling]
history=10000 # Default: 10000
multiplier=3 # Default: 3

[selection]
save_to_clipboard=true

[window]
dimensions = { columns = 500, lines = 180 }
padding = { x = 10, y = 10 }
