[profile.dev]
codegen-units = 1024
debug = false
incremental = true
lto = "thin"
opt-level = 1
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
strip = true
rpath = false

[net]
git-fetch-with-cli = true
# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition"]
# [target.x86_64-unknown-linux-musl]
# linker = "x86_64-linux-musl-gcc"
# [target.aarch64-unknown-linux-gnu]
# linker = "aarch64-linux-gnu-gcc"
# rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition"]
