#!/bin/bash
# Convert a nanosecond epoch timestamp to a readable datetime

if [ -z "$1" ]; then
    echo "Usage: $0 <nanotimestamp>"
    exit 1
fi

echo "Nanotimestamp: $1"
echo "Datetime: $(date -r "$(($1 / 1000000000))" '+%Y-%m-%d %H:%M:%S')"
